### ISSUE TITLE
elasticsearch-1.7.6 does not support the test queries

### ISSUE THREAD

**Issue by northwestwitch** [MatchmakerExchange/reference-server#10]
I noticed that the instructions describe how to download and use elasticsearch-1.7.6. But the package tests fail if you use this version. You should use version 2.x, as stated in the dependencies, right?

**Comment by buske** [comment]
Ah yes, good catch! The docs aren't consistent and don't agree with the current state of the code (which assumes 2.x). The software can work with either, but the trick is making sure that the python packages (elasticsearch and elasticsearch-dsl) match the elasticsearch version. You can see the two options in the INSTALL_REQUIRES definition in setup.py. I'll fix up the docs and try to clarify how to support newer elasticsearch versions, since it looks like they're up to 6.4 now.

**Comment by buske** [comment]
Fixed by #11
